Add methods to lock and unlock app.
superfly/fly-go pull request #73
Opened 2024-06-24 01:03 UTC by gwuah

2024-06-24 01:23 UTC, alichay requested changes

2024-06-24 01:23 UTC, alichay commented on resource_apps.go
> +	`
Is this the right mutation?

2024-06-24 01:23 UTC, alichay commented on resource_apps.go
> +func (client *Client) LockApp(ctx context.Context, input CreateAppInput) (*AppLock, error) {
That type should probably be `AppLockInput` instead of `CreateAppInput`

2024-08-28 20:53 UTC, billyb2 approved these changes
LGTM, though
I worry slightly about having app locks alongside machine leases. Will app locks clear automatically, like how leases do for machines? Also, what exactly will app locks be for?

2024-08-29 08:50 UTC, gwuah commented
@billyb2 
app locks are different from machine locks, and the reason why we're bringing app locks is for https://github.com/superfly/flyctl/pull/3906

yes, they clear automatically, but we will also provide users a failsafe mechanism to unlock their apps, if things really really go south and they need to deploy.

I'm also going to make use of your feature flagging work to slowly release this to users, so we can monitor it. Either way, we need a way to prevent concurrent deployments.

2024-08-29 13:48 UTC, billyb2 commented
> @billyb2 app locks are different from machine locks, and the reason why we're bringing app locks is for [superfly/flyctl#3906](https://github.com/superfly/flyctl/pull/3906)
> 
> yes, they clear automatically, but we will also provide users a failsafe mechanism to unlock their apps, if things really really go south and they need to deploy.
> 
> I'm also going to make use of your feature flagging work to slowly release this to users, so we can monitor it. Either way, we need a way to prevent concurrent deployments.

makes sense 👍🏾

2024-08-29 13:49 UTC, closed without merging